
package publicador;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PropuestaRepetidaException", targetNamespace = "http://publicador/")
public class PropuestaRepetidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PropuestaRepetidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PropuestaRepetidaException_Exception(String message, PropuestaRepetidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PropuestaRepetidaException_Exception(String message, PropuestaRepetidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicador.PropuestaRepetidaException
     */
    public PropuestaRepetidaException getFaultInfo() {
        return faultInfo;
    }

}
