
package publicador;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UsuarioYaColaboraException", targetNamespace = "http://publicador/")
public class UsuarioYaColaboraException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioYaColaboraException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioYaColaboraException_Exception(String message, UsuarioYaColaboraException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UsuarioYaColaboraException_Exception(String message, UsuarioYaColaboraException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicador.UsuarioYaColaboraException
     */
    public UsuarioYaColaboraException getFaultInfo() {
        return faultInfo;
    }

}
